### ISSUE TITLE
Message not delivered to contact

### ISSUE THREAD

**Issue by Rohitkumarvarma-369** [Zaid-maker/cyclone-messaging#3]
Is the app still working? cause  Msg is not getting received at the other end of the conversation, can you please check if this is due to dependency versions?

**Comment by Zaid-maker** [comment]
Yes I am aware of this issue the server is having some problem connecting
to frontend shut down the server until I fix the problem :)

**Comment by Zaid-maker** [comment]
But no worries I am working on the fix.
